apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-microproject-log-pvc
  namespace: virtu
  labels:
    app: app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi