apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-microproject-log-pv
  namespace: virtu
  labels:
    type: local
    app: app
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/app