apiVersion: v1
kind: PersistentVolume
metadata:
  name: microproject-pv
  namespace: virtu
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/microproject-data # Chemin local sur le nœud Kubernetes (peut être changé selon votre configuration)
  storageClassName: manual
