apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microproject-pvc
  namespace: virtu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
